baseURL = 'https://thingly.net/'
languageCode = 'en-us'
title = 'thingly.net'

[menu]

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Résumé"
url = "/resume/"
weight = 2

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"
