baseURL = 'https://thingly.net/'
languageCode = 'en-us'
title = 'thingly.net'

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Resume"
url = "/resume.html"
weight = 3

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"
